using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum ParticleDisplayMode
{
    Density = 0,
    Velocity = 1,
    Energy = 2
}

public class NebulaParticleDisplay : MonoBehaviour
{
    
    public Shader shader; // Set to the particle shader 'Particle3D' in the inspector
    
    [Header("Mesh Settings")]
    public Mesh mesh; // the mesh used for the particles (generated by MeshGenerator.cs at runtime)

    [Header("Particle Settings")]
    public float scale;
    public Color colour;
    Material material;

    [Header("Display Settings")]
    public Gradient colourMap;
    public int gradientResolution;
    public float densityDisplayMin;
    public float densityDisplayMax;
    public float velocityDisplayMin;
    public float velocityDisplayMax;
    public float energyDisplayMin;
    public float energyDisplayMax;
    public ParticleDisplayMode displayMode;

    ComputeBuffer argsBuffer;
    Bounds bounds;
    Texture2D gradientTexture;
    bool needsUpdate;

    // Creates a material from the 'shader' and sets the values of the position and velocity buffers
    // It then creates an argument buffer and the bounds to spawn the particles in
    public void Init(NebulaParticleSimulator sim)
    {
        material = new Material(shader);
        material.SetBuffer("positions", sim.positionBuffer);
        material.SetBuffer("velocities", sim.velocityBuffer);
        material.SetBuffer("densities", sim.densityBuffer);
        material.SetBuffer("energies", sim.InternalEnergyBuffer);

        argsBuffer = ComputeHelper.CreateArgsBuffer(mesh, sim.positionBuffer.count);
        bounds = new Bounds(Vector3.zero, Vector3.one * 10000);
    }

    // Draws the particles in the scene
    void LateUpdate()
    {
        if (shader != null)
        {
            UpdateSettings();
            Graphics.DrawMeshInstancedIndirect(mesh, 0, material, bounds, argsBuffer); // the function responsible for drawing the particles
        }
    }

    // Updates any settings in the material when necessary
    void UpdateSettings()
    {
        if (needsUpdate)
        {
            needsUpdate = false;
            TextureFromGradient(ref gradientTexture, gradientResolution, colourMap);
            material.SetTexture("ColourMap", gradientTexture);
            material.SetFloat("densityMin", densityDisplayMin);
            material.SetFloat("densityMax", densityDisplayMax);
            material.SetFloat("scale", scale);
            material.SetFloat("velocityMin", velocityDisplayMin);
            material.SetFloat("velocityMax", velocityDisplayMax);
            material.SetFloat("energyMin", energyDisplayMin);
            material.SetFloat("energyMax", energyDisplayMax);
            material.SetInt("displayType", (int)displayMode);

            // check if the below can be removed
            material.SetColor("colour", colour);

            Vector3 s = transform.localScale;
            transform.localScale = Vector3.one;
            var localToWorldMatrix = transform.localToWorldMatrix;
            transform.localScale = s;
            material.SetMatrix("localToWorld", localToWorldMatrix);
        }
    }

    // Generates a 2D texture from the colour map, with the specified width and filter mode
    void TextureFromGradient(ref Texture2D texture, int width, Gradient gradient, FilterMode filter = FilterMode.Bilinear)
    {
        if (texture == null)
        {
            texture = new Texture2D(width, 1);
        }
        else if (texture.width != width)
        {
            texture.Reinitialize(width, 1);
        }

        if (gradient == null)
        {
            gradient = new Gradient();
            gradient.SetKeys(new GradientColorKey[] {new GradientColorKey(Color.black, 0), new GradientColorKey(Color.black, 1)},
                             new GradientAlphaKey[] {new GradientAlphaKey(1, 0), new GradientAlphaKey(1, 1) });
        }

        texture.wrapMode = TextureWrapMode.Clamp;
        texture.filterMode = filter;

        Color[] cols = new Color[width];
        for (int i = 0; i < cols.Length; i++)
        {
            float t = i/(cols.Length - 1.0f);
            cols[i] = gradient.Evaluate(t);
        }
        texture.SetPixels(cols);
        texture.Apply();
    }

    // Automatically called when the variables are changed in the editor
    // this is used to update the material settings when the user changes the values in the inspector
    private void OnValidate()
    {
        needsUpdate = true;
    }

    // Clears the memory of the argument buffer when the program is closed
    private void OnDestroy()
    {
        ComputeHelper.Release(argsBuffer);
    }
}
