using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum ParticleDisplayMode
{
    Density = 0,
    Velocity = 1,
    Entropy = 2,
    Temperature = 3,
    SmoothingRadius = 4,
    HydrogenRatio = 5
}

public class NebulaParticleDisplay : MonoBehaviour
{
    
    public Shader shader; // Set to the particle shader 'Particle3D' in the inspector
    
    [Header("Mesh Settings")]
    public Mesh mesh; // the mesh used for the particles (generated by MeshGenerator.cs at runtime)

    [Header("Particle Settings")]
    public float scale;
    Material material;

    [Header("Display Settings")]
    public Gradient colourMap;
    public int gradientResolution;
    public Vector2 densityRange;
    public Vector2 velocityRange;
    public Vector2 entropyRange;
    public Vector2 temperatureRange;
    public Vector2 SmoothingRange;
    public Vector2 hydroRange;
    public ParticleDisplayMode displayMode;

    ComputeBuffer argsBuffer;
    Bounds bounds;
    Texture2D gradientTexture;
    bool needsUpdate;

    // Creates a material from the 'shader' and sets the values of the position and velocity buffers
    // It then creates an argument buffer and the bounds to spawn the particles in
    public void Init(NebulaParticleSimulator sim)
    {
        material = new Material(shader);
        material.SetBuffer("particles", sim.particleBuffer);

        argsBuffer = ComputeHelper.CreateArgsBuffer(mesh, sim.particleBuffer.count);
        bounds = new Bounds(Vector3.zero, Vector3.one * 10000);
    }

    // Draws the particles in the scene
    void LateUpdate()
    {
        if (shader != null)
        {
            UpdateSettings();
            Graphics.DrawMeshInstancedIndirect(mesh, 0, material, bounds, argsBuffer); // the function responsible for drawing the particles
        }
    }

    // Updates any settings in the material when necessary
    void UpdateSettings()
    {
        if (needsUpdate)
        {
            needsUpdate = false;
            TextureFromGradient(ref gradientTexture, gradientResolution, colourMap);
            material.SetTexture("ColourMap", gradientTexture);
            material.SetFloat("scale", scale);
            material.SetInt("displayType", (int)displayMode);

            Vector2 density = new Vector2(densityRange.x, (1.0f/(densityRange.y - densityRange.x)));
            Vector2 velocity = new Vector2(velocityRange.x, (1.0f/(velocityRange.y - velocityRange.x)));
            Vector2 entropy = new Vector2(entropyRange.x, (1.0f/(entropyRange.y - entropyRange.x)));
            Vector2 temperature = new Vector2(temperatureRange.x, (1.0f/(temperatureRange.y - temperatureRange.x)));
            Vector2 smoothing = new Vector2(SmoothingRange.x, (1.0f/(SmoothingRange.y - SmoothingRange.x)));
            Vector2 hydro = new Vector2(hydroRange.x, (1.0f/(hydroRange.y - hydroRange.x)));

            material.SetVector("densityRange", density);
            material.SetVector("velocityRange", velocity);
            material.SetVector("energyRange", entropy);
            material.SetVector("tempRange", temperature);
            material.SetVector("smoothingRange", smoothing);
            material.SetVector("hydroRange", hydro);

            Vector3 s = transform.localScale;
            transform.localScale = Vector3.one;
            var localToWorldMatrix = transform.localToWorldMatrix;
            transform.localScale = s;
            material.SetMatrix("localToWorld", localToWorldMatrix);
        }
    }

    // Generates a 2D texture from the colour map, with the specified width and filter mode
    void TextureFromGradient(ref Texture2D texture, int width, Gradient gradient, FilterMode filter = FilterMode.Bilinear)
    {
        if (texture == null)
        {
            texture = new Texture2D(width, 1);
        }
        else if (texture.width != width)
        {
            texture.Reinitialize(width, 1);
        }

        if (gradient == null)
        {
            gradient = new Gradient();
            gradient.SetKeys(new GradientColorKey[] {new GradientColorKey(Color.black, 0), new GradientColorKey(Color.black, 1)},
                             new GradientAlphaKey[] {new GradientAlphaKey(1, 0), new GradientAlphaKey(1, 1) });
        }

        texture.wrapMode = TextureWrapMode.Clamp;
        texture.filterMode = filter;

        Color[] cols = new Color[width];
        for (int i = 0; i < cols.Length; i++)
        {
            float t = i/(cols.Length - 1.0f);
            cols[i] = gradient.Evaluate(t);
        }
        texture.SetPixels(cols);
        texture.Apply();
    }

    // Automatically called when the variables are changed in the editor
    // this is used to update the material settings when the user changes the values in the inspector
    private void OnValidate()
    {
        needsUpdate = true;
    }

    // Clears the memory of the argument buffer when the program is closed
    private void OnDestroy()
    {
        ComputeHelper.Release(argsBuffer);
    }
}
